### ISSUE TITLE
Change attack function

### ISSUE THREAD

**Issue by CStanKonrad** [Plastermind/starwars#10]
No damage when shield of attacker = 0

**Comment by Plastermind** [comment]
Chyba specjalnie to zostawiłeś, żebym miał co zrobić :P 
Zmieniłem trzy razy .getShield() >= 0, na > 0
Dobrze? :D

**Comment by Plastermind** [comment]
Chyba specjalnie to zostawiłeś, żebym miał co zrobić :P
Zmieniłem trzy razy .getShield() >= 0, na > 0
Dobrze? :D
